CREATE TABLE BookUserRelation (
UserID INT NOT NULL,
BookID INT NOT NULL,
FOREIGN KEY (UserID) 
	REFERENCES Users(ID)
	ON DELETE CASCADE,
FOREIGN KEY (BookID) 
	REFERENCES Books(ID)
	ON DELETE CASCADE,
UNIQUE(UserID, BookID)
);
